### ISSUE TITLE
Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by ShoraiK** [ShoraiK/Zorabot#1]
El token de openweather está provocando una excepción al ejecutarse.

Adjunto log:

```
SyntaxError: Unexpected token ILLEGAL
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

**Comment by ShoraiK** [comment]
Ya se ha solucionado.
